### ISSUE TITLE
TER release

### ISSUE THREAD

**Issue by MK-42** [sourcebroker/urlguard#3]
unfortunately one of our deployments can not yet be upgraded to composer and I couldn't find your extension in TER. Would you consider pushing it there?
Having to update it by hand without EM support is errorprone and cumbersome.

**Comment by kszymukowicz** [comment]
hello

I do not use TER since ages now because all TYPO3 instances I have are composer based so for now I do not consider to put it into TER as putting ext manually to TER is cumbersome and time consuming. I also have no time to implement auto TER upload on git tagging. 

However if you really want you can sponsor feature: "auto TER upload on git tagging".

**Comment by MK-42** [comment]
Thanks for your response. How would you like the auto-publish to happen? helhum is doing it via travis directly on github. I could try to provide a PR with the needed configuration if you are interested in that. Otherwise I would probably have to go the manual route.

**Comment by kszymukowicz** [comment]
Helhum way via travis is ok. I am waiting for PR then. Thanks for helping!

**Comment by kszymukowicz** [comment]
Done finally :)
